BlankSpace/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlankSpace.Models
{
    public class Driver
    {
        [Key]
        public int DriverId { get; set; }
        public string Name { get; set; }
        public Int64 Mobile { get; set; }
        public string Address  { get; set; }
        public string LicenseNumber { get; set; }

    }
}

BlankSpace/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlankSpace.Database;
using BlankSpace.Models;
using BlankSpace.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlankSpace.Controllers
{
    public class DriverController : Controller
    {
        private readonly DatabaseContext _context;
        [TempData]
        public string msg { get; set; }
        public DriverController(DatabaseContext context)
        {
            _context = context;
        }
        public IActionResult NewDriver()
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public IActionResult NewDriver(DriverVm d)
        {
            var i = _context.Drivers.Where(x => x.LicenseNumber == d.LicenseNumber).FirstOrDefault();
            Driver di = new Driver()
            { DriverId = d.DriverVmId,
                Name = d.Name,
                Address = d.Address,
                LicenseNumber = d.LicenseNumber,
                Mobile = d.Mobile
            };
            if(i==null)
            {
                _context.Drivers.Add(di);
                _context.SaveChanges();
                msg = "New Driver Added!";
                return RedirectToAction(nameof(DriverList));
            }
            else
            {
                msg = "Driver Already Exist!";
                return RedirectToAction(nameof(NewDriver));
            }
         
          
        }

        public IActionResult DriverList()
        {
            if (HttpContext.Session.GetString("UserRole") != null)
            {
                var s = _context.Drivers.AsNoTracking().ToList();
                var dr = new List<DriverVm>();
                int c = 1;
                foreach (var item in s)
                {
                    DriverVm se = new DriverVm()
                    {
                        DriverVmId = item.DriverId,
                        Name = item.Name,
                        Address = item.Address,
                        Mobile = item.Mobile,
                        LicenseNumber = item.LicenseNumber

                    };
                    se.DriverSerial = c;
                    c++;
                    dr.Add(se);
                }
                return View(dr);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        public IActionResult UpdateDriver(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var item = _context.Drivers.AsNoTracking().Where(s => s.DriverId == id).FirstOrDefault();
                DriverVm se = new DriverVm()
                {
                    DriverVmId = item.DriverId,
                    Name = item.Name,
                    Address = item.Address,
                    Mobile = item.Mobile,
                    LicenseNumber = item.LicenseNumber,

                };
                return View(se);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        [HttpPost]
        public IActionResult UpdateDriver(DriverVm d)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                //var i = _context.Drivers.Where(x => x.LicenseNumber == d.LicenseNumber|| x.Name == d.Name).FirstOrDefault();
                Driver di = new Driver()
                {
                    DriverId = d.DriverVmId,
                    Name = d.Name,
                    Address = d.Address,
                    LicenseNumber = d.LicenseNumber,
                    Mobile = d.Mobile

                };
              
                    _context.Drivers.Update(di);
                    _context.SaveChanges();
                    msg = "Edited Successfully!";
                    return RedirectToAction(nameof(DriverList));
             
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        public IActionResult DeleteDriver(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var item = _context.Drivers.AsNoTracking().Where(s => s.DriverId == id).FirstOrDefault();
                DriverVm se = new DriverVm()
                {
                    DriverVmId = item.DriverId,
                    Name = item.Name,
                    Address = item.Address,
                    Mobile = item.Mobile,
                    LicenseNumber = item.LicenseNumber,

                };
                return View(se);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        [HttpPost]
        public IActionResult DeleteDriver(DriverVm se)
        {
            _context.Drivers.Remove(_context.Drivers.AsNoTracking().Where(s => s.DriverId == se.DriverVmId).FirstOrDefault());
            _context.SaveChanges();
            msg = "Deleted Successfully";
            return RedirectToAction("DriverList");
        }
        public IActionResult DriverDetails(int id)

        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var item = _context.Drivers.AsNoTracking().Where(s => s.DriverId == id).FirstOrDefault();
                DriverVm se = new DriverVm()
                {
                    DriverVmId = item.DriverId,
                    Name = item.Name,
                    Address = item.Address,
                    Mobile = item.Mobile,
                    LicenseNumber = item.LicenseNumber,

                };
                return View(se);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        public IActionResult AssignBus()
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var driver = _context.Drivers.AsNoTracking().ToList();
                ViewBag.Driver = new SelectList(driver, "DriverId", "Name");
                var bus = _context.Buses.AsNoTracking().ToList();
                ViewBag.Bus = new SelectList(bus, "BusId", "CoachName");


                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        [HttpPost]
        public IActionResult AssignBus(AssignedDriverVm a)
        {
            var sa = _context.AssignedDrivers.AsNoTracking().
                Where(s => s.BusId == a.BusId || s.DriverId == a.DriverId).FirstOrDefault();
            if(sa!=null)
            {
                msg = "Driver Already Assigned For This Bus";
                return RedirectToAction(nameof(AssignBus));
            }

            AssignedDriver ab = new AssignedDriver() {
                AssignedDriverId = 0,
                BusId = a.BusId,
                DriverId = a.DriverId
            };
            _context.AssignedDrivers.Add(ab);
            _context.SaveChanges();
            msg = "Bus Assign Successfully";
            return RedirectToAction("AssignBusList");
        }
        public IActionResult AssignBusList()
        {
            if (HttpContext.Session.GetString("UserRole") != null)
            {
                var assignDriverList = _context.AssignedDrivers.
                                AsNoTracking().Include(s => s.Bus).
                                Include(s => s.Driver).ToList();
                var sent = new List<AssignedDriverVm>();
                int c = 1;
                foreach (var item in assignDriverList)
                {
                    AssignedDriverVm a = new AssignedDriverVm()
                    {

                        DriverName = item.Driver.Name,
                        CoachName = item.Bus.CoachName,
                        AssignedDriverId = item.AssignedDriverId,
                        Serial = c

                    };
                    c++;
                    sent.Add(a);

                }
                return View(sent);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        public IActionResult DetailsAssignDriver(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var assignDriver = _context.AssignedDrivers.
                                  AsNoTracking().Include(s => s.Bus).
                                  Include(s => s.Driver).Where(s => s.AssignedDriverId == id).
                                  FirstOrDefault();


                AssignedDriverVm a = new AssignedDriverVm()
                {

                    DriverName = assignDriver.Driver.Name,
                    CoachName = assignDriver.Bus.CoachName,
                    BusNumber = assignDriver.Bus.BusNumber,
                    DriverMobile = assignDriver.Driver.Mobile,
                    TotalSeat = assignDriver.Bus.TotalSeat


                };


                return View(a);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        public IActionResult DeleteAssignedDriver(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var assignDriver = _context.AssignedDrivers.
                                  AsNoTracking().Include(s => s.Bus).

BlankSpace/Views/Driver/AssignBus.cshtml
@model BlankSpace.ViewModels.AssignedDriverVm

@{
    ViewData["Title"] = "AssignBus";
}




<h4 style="text-align:center"><strong>Assign Driver to Bus</strong> </h4>
<hr />
<div class="row">
    @if (TempData["msg"] != null)
    {
        <div class="alert alert-info text-center" role="alert">
            <button type="button" class="close" aria-label="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
            @TempData["msg"]
        </div>
    }
    <div class="col-md-4 col-md-offset-4">

        <form asp-action="AssignBus">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BusId" class="control-label h4"></label>
                <select asp-items="@ViewBag.Bus" asp-for="BusId" class="form-control">
                    <option hidden disabled selected>Please Select Bus</option>
                </select>
                <span asp-validation-for="BusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label h4"></label>
                <select asp-items="@ViewBag.Driver" asp-for="DriverId" class="form-control">
                    <option hidden disabled selected>Please Select Driver</option>
                </select>
                <span asp-validation-for="DriverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
        <div>
            <a asp-action="AssignBusList">Back to List</a>
        </div>
    </div>
</div>

BlankSpace/Views/Driver/AssignBusList.cshtml
@model List<BlankSpace.ViewModels.AssignedDriverVm>

<p class="h2" style="text-align:center;">Assign Bus To Driver List<br /><div style="border-bottom:1px solid #686868"></div> </p>
@if (TempData["msg"] != null)
{
    <div class="alert alert-info text-center" role="alert">
        <button type="button" class="close" aria-label="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["msg"]
    </div>
}
<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th class="h3">
                Serial No
            </th>
            <th class=" h3 ">
                Diver Name
            </th>
            <th class=" h3  ">
                Assigned Bus
            </th>

            <th class=" h3  ">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td class=" h4  ">@item.Serial</td>
                <td class=" h4  ">@item.DriverName</td>
                <td class=" h4  ">@item.CoachName</td>
                <td class=" h4  ">
                    @*<a asp-action="UpdateAssignedDriver" asp-controller="Driver" asp-route-id="@item.AssignedDriverId"><i class="fa fa-pencil-square-o" style="font-size:25px;color:green"></i></a>
                    &nbsp;&nbsp;&nbsp;*@
                    <a asp-action="DetailsAssignDriver" asp-controller="Driver" asp-route-id="@item.AssignedDriverId"><i class="fa fa-info-circle" style="font-size:25px;color:dodgerblue"></i></a>
                    &nbsp;&nbsp;&nbsp;
                    <a asp-action="DeleteAssignedDriver" asp-controller="Driver" asp-route-id="@item.AssignedDriverId"><i class="fa fa-trash" style="font-size:25px;color:red"></i></a>

                </td>
            </tr>
        }
    </tbody>
</table>

BlankSpace/Views/Driver/DeleteAssignedDriver.cshtml
@model BlankSpace.ViewModels.AssignedDriverVm

@{
    ViewData["Title"] = "DeleteAssignedDriver";
}

<h2 style="text-align:center">Detele Assigned Driver</h2>


<hr />
<h3 style="text-align:center">Are you sure you want to delete this?</h3>
<div class="col-md-4 col-md-offset-4">


    <h4 style="text-align:center">
        Driver Details
    </h4>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.DriverName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriverMobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverMobile)
        </dd>



    </dl>

    <h4 style="text-align:center">
        Bus Details
    </h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CoachName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CoachName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalSeat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalSeat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BusNumber)
        </dd>

    </dl>
    <form asp-action="DeleteAssignedDriver">
        <input asp-for="AssignedDriverId" type="hidden" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="AssignBusList">Back to List</a>
    </form>

</div>

BlankSpace/Views/Driver/DeleteDriver.cshtml
@model BlankSpace.ViewModels.DriverVm

@{
    ViewData["Title"] = "Delete Driver";
}

<h2 style="text-align:center">Delete Driver</h2>
<hr />
<center><h3>Are you sure you want to delete this?</h3> </center>
<div class="col-md-5 col-md-offset-4">

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LicenseNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LicenseNumber)
        </dd>
    </dl>

    <form asp-action="DeleteDriver">
        <input type="hidden" asp-for="DriverVmId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="DriverList">Back to List</a>
    </form>
</div>

BlankSpace/Views/Driver/DetailsAssignDriver.cshtml
@model BlankSpace.ViewModels.AssignedDriverVm

@{
    ViewData["Title"] = "DetailsAssignBus";
}

<h3 style="text-align:center"> Assigned Bus Driver Details</h3>
<hr />

<div class="col-md-4 col-md-offset-4">

    <h4 style="text-align:center">
        Driver Details
    </h4>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.DriverName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriverMobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverMobile)
        </dd>



    </dl>

    <h4 style="text-align:center">
        Bus Details
    </h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CoachName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CoachName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalSeat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalSeat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BusNumber)
        </dd>

    </dl>
    <div>

        <a asp-action="AssignBusList">Back to List</a>
    </div>

</div>

BlankSpace/Views/Driver/DriverDetails.cshtml
@model BlankSpace.ViewModels.DriverVm

@{
    ViewData["Title"] = "DriverDetails";
}
<h2 style="text-align:center">Driver Details</h2>


<hr />

<div class="col-md-5 col-md-offset-4">

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LicenseNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LicenseNumber)
        </dd>
    </dl>
    <div>

        <a asp-action="DriverList">Back to List</a>
    </div>
</div>

BlankSpace/Views/Driver/DriverList.cshtml
@model List<BlankSpace.ViewModels.DriverVm>

<p class="h2" style="text-align:center;">Driver List<br /><div style="border-bottom:1px solid #686868"></div> </p>
@if (TempData["msg"] != null)
{
    <div class="alert alert-info text-center" role="alert">
        <button type="button" class="close" aria-label="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["msg"]
    </div>
}

<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th class="h3">
                Serial No
            </th>
            <th class=" h3 ">
                Driver Name
            </th>
            <th class=" h3  ">
                Mobile Number
            </th>
            <th class=" h3  ">
                License Number
            </th>
            <th class=" h3  ">
                Address
            </th>
            <th class=" h3  ">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td class=" h4  ">@item.DriverSerial</td>
                <td class=" h4  ">@item.Name</td>
                <td class=" h4  ">@item.Mobile</td>
                <td class=" h4  ">@item.LicenseNumber</td>
                <td class=" h4  ">@item.Address</td>
                <td class=" h4  ">
                    <a asp-action="UpdateDriver" asp-controller="Driver" asp-route-id="@item.DriverVmId"><i class="fa fa-pencil-square-o" style="font-size:25px;color:green"></i></a>
                    &nbsp;&nbsp;&nbsp;
                    <a asp-action="DriverDetails" asp-controller="Driver" asp-route-id="@item.DriverVmId"><i class="fa fa-info-circle" style="font-size:25px;color:dodgerblue"></i></a>
                    &nbsp;&nbsp;&nbsp;
                    <a asp-action="DeleteDriver" asp-controller="Driver" asp-route-id="@item.DriverVmId"><i class="fa fa-trash" style="font-size:25px;color:red"></i></a>

                </td>
            </tr>
        }
    </tbody>
</table>

BlankSpace/Views/Driver/NewDriver.cshtml
@model BlankSpace.ViewModels.DriverVm

@{
    ViewData["Title"] = "NewDriver";
}




<h2 style="text-align:center">New Driver</h2>
<hr />
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @if (TempData["msg"] != null)
        {
            <div class="alert alert-info text-center" role="alert">
                <button type="button" class="close" aria-label="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                @TempData["msg"]
            </div>
        }
        <form asp-action="NewDriver">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label h4"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label h4"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label h4"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LicenseNumber" class="control-label h4"></label>
                <input asp-for="LicenseNumber" class="form-control" />
                <span asp-validation-for="LicenseNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
        <div>
            <a asp-action="DriverList">Back to List</a>
        </div>
    </div>
</div>

BlankSpace/Views/Driver/UpdateAssignedDriver.cshtml
@model BlankSpace.ViewModels.AssignedDriverVm

@{
    ViewData["Title"] = "UpdateAssignBus";
}


<h4 style="text-align:center" > Update Assign Driver to Bus</h4>

<hr />
<div class="row">

    <div class="col-md-4 col-md-offset-4">

        <form asp-action="UpdateAssignedDriver">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="AssignedDriverId" type="hidden" />
            <div class="form-group">
                <label asp-for="BusId" class="control-label h4"></label>
                <select asp-items="@ViewBag.Bus" asp-for="BusId" class="form-control">
                    <option hidden disabled selected>Please Select Bus</option>
                </select>
                <span asp-validation-for="BusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label h4"></label>
                <select asp-items="@ViewBag.Driver" asp-for="DriverId" class="form-control">
                    <option hidden disabled selected>Please Select Driver</option>
                </select>
                <span asp-validation-for="DriverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </form>
        <div>
            <a asp-action="AssignBusList">Back to List</a>
        </div>
    </div>
</div>

BlankSpace/Views/Driver/UpdateDriver.cshtml
@model BlankSpace.ViewModels.DriverVm

@{
    ViewData["Title"] = "UpdateDriver";
}

<h2 style="text-align:center">Update Driver</h2>

<hr />
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @if (TempData["msg"] != null)
        {
            <div class="alert alert-info text-center" role="alert">
                <button type="button" class="close" aria-label="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                @TempData["msg"]
            </div>
        }

        <form asp-controller="Driver" asp-action="UpdateDriver" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="DriverVmId" type="hidden" />
            <input asp-for="LicenseNumber" type="hidden" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="LicenseNumber" class="control-label"></label>
                <input asp-for="LicenseNumber" class="form-control" />
                <span asp-validation-for="LicenseNumber" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
        <div>
            <a asp-action="DriverList">Back to List</a>
        </div>
    </div>
</div>