BlankSpace/Models/Agent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlankSpace.Models
{
    public class Agent
    {   
        [Key]
        public int AgentId { get; set; }
        public Int64 Mobile { get; set; } 
        public string Name { get; set; }
        public DateTime DOB { get; set; }
        public string Address { get; set; }
        public virtual ICollection<TicketReservation> TicketReservations { get; set; }

    }
}

BlankSpace/Controllers/TicketBookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlankSpace.Database;
using BlankSpace.Helper;
using BlankSpace.Models;
using BlankSpace.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlankSpace.Controllers
{
    public class TicketBookingController : Controller
    {
        private readonly DatabaseContext _context;

        public TicketBookingController(DatabaseContext context)
        {
            _context = context;
        }

        public JsonResult CheckRoute(int StartingFrom)
        {
            var n = _context.BusSchedules.AsNoTracking().Where(s => s.StartingFrom == StartingFrom).FirstOrDefault();
            if (n == null)
            {
                return Json(data: false);
            }
            else
            {
                return Json(data: true);
            }
        }
        //[HttpGet]
        //[HttpPost]
        //public JsonResult CheckDes(int id)
        //{
        //    var d = _context.BusSchedules.AsNoTracking().Where(s => s.BusScheduleId == id).FirstOrDefault();
        //    return Json(d.Destination);
        //}
        [HttpGet]
        [HttpPost]
        public JsonResult checkboth(int id, int id2)
        {
            var d = _context.BusSchedules.AsNoTracking().Where(s => s.StartingFrom == id && s.Destination == id2).ToList();
            var bus = _context.Buses.ToList();
            var de = from i in d
                     join b in bus on i.BusId equals b.BusId
                     select new
                     {
                         BusId = i.BusId,
                         CoachName = b.CoachName
                     };

            var slist = new SelectList(de, "BusId", "CoachName");
            return Json(slist);
        }

        [HttpGet]
        [HttpPost]
        public JsonResult checktime(int id, int id2)
        {
            var d = _context.BusSchedules.AsNoTracking().Where(s => s.StartingFrom == id && s.Destination == id2).FirstOrDefault();
            return Json(d.Time);
        }
        public JsonResult checkid(int id, int id2)
        {
            var d = _context.BusSchedules.AsNoTracking().Where(s => s.StartingFrom == id && s.Destination == id2).FirstOrDefault();
            return Json(d.BusScheduleId);
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserRole") == "2")
            {
                var start = _context.Places.AsNoTracking().ToList();
                ViewBag.Start = new SelectList(start, "PlaceId", "PlaceName");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Agent()
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public IActionResult Booking(BookingVm b)
        {
            var TicketList = _context.TicketReservations.
                 AsNoTracking().Include(a => a.BusSchedule).
                 Where(s => s.BusSchedule.BusId == b.BusId && s.BusSchedule.StartingFrom == b.StartingFrom
                 && s.BusSchedule.Destination == b.Destination && s.Date == b.Date).ToList();
            if (TicketList.Count() == 0)
            {
                var Seat = _context.Buses.Where(s => s.BusId == b.BusId).FirstOrDefault();
                var Tickets = GenarateTicket.Ticket(Seat.TotalSeat, b.BookingVmId, b.Date);

                var SeatSent = new List<TicketReservationVm>();
                foreach (var item in Tickets)
                {
                    _context.TicketReservations.Add(item);
                    _context.SaveChanges();
                    TicketReservationVm a = new TicketReservationVm()
                    {
                        TicketReservationId = item.TicketReservationId,
                        ConfirmStatus = item.ConfirmStatus,
                        Date = item.Date,
                        AgentId = item.AgentId,
                        PassengerId = item.PassengerId,
                        BusScheduleId = item.BusScheduleId,
                        SeatNumber = item.SeatNumber
                    };
                    if (item.ConfirmStatus == false)
                    {
                        a.MightBeReserve = true;
                    }
                    else
                    {
                        a.MightBeReserve = false;
                    }
                    SeatSent.Add(a);
                }
                var price = _context.BusSchedules.AsNoTracking().
                    Where(s => s.BusScheduleId == Tickets[1].BusScheduleId).FirstOrDefault();
                ViewBag.Price = price.TicketPrice;
                return View(SeatSent);
            }
            else
            {
                var Ticket = _context.TicketReservations.
                 AsNoTracking().Include(a => a.BusSchedule).
                 Where(s => s.BusSchedule.BusId == b.BusId && s.BusSchedule.StartingFrom == b.StartingFrom
                 && s.BusSchedule.Destination == b.Destination
                 && s.Date.Month == b.Date.Month
                 && s.Date.Year == b.Date.Year
                 && s.Date.Day == b.Date.Day).ToList();

                var SeatSent = new List<TicketReservationVm>();
                foreach (var item in Ticket)
                {

                    TicketReservationVm a = new TicketReservationVm()
                    {
                        TicketReservationId = item.TicketReservationId,
                        ConfirmStatus = item.ConfirmStatus,
                        Date = item.Date,
                        AgentId = item.AgentId,
                        PassengerId = item.PassengerId,
                        BusScheduleId = item.BusScheduleId,
                        SeatNumber = item.SeatNumber
                    };
                    if (item.ConfirmStatus == false)
                    {
                        a.MightBeReserve = true;
                    }
                    SeatSent.Add(a);
                }
                var price = _context.BusSchedules.AsNoTracking().
                    Where(s => s.BusScheduleId == Ticket[1].BusScheduleId).FirstOrDefault();
                ViewBag.Price = price.TicketPrice;
                return View(SeatSent);
            }
        }

        [HttpPost]
        public IActionResult ConfirmTicket(List<TicketReservationVm> a, string PassengerName, int PassengerMobile)
        {
            var ab = a.Where(s => s.ConfirmStatus == true && s.MightBeReserve == true).ToList();

            if (ab.Count != 0)
            {
                Passenger p = new Passenger()
                {
                    PassengerId = 0,
                    Mobile = PassengerMobile,
                    Name = PassengerName

                };
                _context.Passengers.Add(p);
                _context.SaveChanges();

                var seatList = new List<string>();

                foreach (var item in ab)
                {
                    TicketReservation c = new TicketReservation()
                    {
                        TicketReservationId = item.TicketReservationId,
                        AgentId = item.AgentId,
                        ConfirmStatus = item.ConfirmStatus,
                        BusScheduleId = item.BusScheduleId,
                        Date = item.Date,
                        PassengerId = p.PassengerId,
                        SeatNumber = item.SeatNumber
                    };

                    _context.TicketReservations.Update(c);
                    _context.SaveChanges();
                    seatList.Add(c.SeatNumber);
                }

                var ss = _context.BusSchedules.AsNoTracking().Include(sp => sp.Bus).ToList();
                var pa = _context.Places.AsNoTracking().ToList();
                var pp = _context.Places.AsNoTracking().ToList();
                var s = from abc in ss
                        join ab1 in pa on abc.StartingFrom equals ab1.PlaceId
                        join aaab in pp on abc.Destination equals aaab.PlaceId
                        where abc.BusScheduleId == ab[0].BusScheduleId
                        select new
                        {
                            DestinationName = aaab.PlaceName,
                            StartingFromName = ab1.PlaceName,
                            Time = abc.Time,

                            CoachName = abc.Bus.CoachName,
                            TicketPrice = abc.TicketPrice,

                        };

                TicketVm t = new TicketVm()
                {
                    PassengerName = p.Name,
                    Mobile = p.Mobile,
                    Seat = seatList,
                };
                foreach (var item in s)
                {
                    t.Destination = item.DestinationName;
                    t.StartFrom = item.StartingFromName;

                    t.TicketPrice = item.TicketPrice;
                    t.Date = a[0].Date;
                    t.BusName = item.CoachName;
                    t.Time = item.Time;
                }
                t.TotalCost = t.TicketPrice * ab.Count();
                return View(t);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Scripts()
        {
            if (HttpContext.Session.GetString("UserRole") == "2")
            {
                var a = _context.Buses.AsEnumerable().ToList();
                ViewBag.Bus = new SelectList(a, "BusId", "CoachName");
                return View();
            }
            else
            {

BlankSpace/Views/TicketBooking/Agent.cshtml
@{
    ViewData["Title"] = "Agent";
}

<h2>Agent</h2>

BlankSpace/Views/TicketBooking/Booking.cshtml
@model List<BlankSpace.ViewModels.TicketReservationVm>
@{
    ViewData["Title"] = "Booking";
}

@{var total = Model.Count();
}
<style>

    .required-field::before {
  content: "*";
  color: red;
}
    .AvailableCircle {
  height: 20px;
  width: 20px;
  background-color: green;
  border-radius: 50%;
  display: inline-block;
  
}
    .BookedCircle {
  height: 20px;
  width: 20px;
  background-color: red;
  border-radius: 50%;
  display: inline-block;
 
}
    .SelectedCircle {
  height: 20px;
  width: 20px;
  background-color: black;
  border-radius: 50%;
  display: inline-block;
  
 
}
</style>
<form id="ImageStatus" asp-action="ConfirmTicket" method="post">
    <h2 class="text-center"> Ticket Panel Booking</h2>
    <hr />
   
    <div class="row">
        <div class="col-md-3 col-md-offset-3">
            <label class="h3"> Bus Tickets </label>
            <br />
            <br />
            @{int i, k; }
            @for (i = 0; i < Model.Count(); i++)
            {
                k = i;
                @if (k % 4 == 0 && k > 0)
                {
                    <br />
                    <br />
                    <br />
                }

                <div class="col-md-1 col-lg-1 col-sm-2 col-xs-4" style="padding:0px;border:0px;width:50px">
                    @if (Model[i].ConfirmStatus == true)
                    {

                        <img src="~/images/RedGood.svg" class="img-responsive" style="width:30px;height:30px" alt="@i" asp-append-version="true" />
                    }
                    else
                    {


                        <img src="~/images/Green.svg" class="img-responsive" style="width:30px;height:30px" alt="@i" asp-append-version="true" />
                    }
                    <span>@Model[i].SeatNumber</span>
                    <input type="hidden" asp-for="@Model[i].PassengerId" />
                    <input type="hidden" asp-for="@Model[i].TicketReservationId" />
                    <input type="hidden" asp-for="@Model[i].AgentId" />
                    <input type="hidden" asp-for="@Model[i].Date" />
                    <input type="hidden" asp-for="@Model[i].ConfirmStatus" id="status" />
                    <input type="hidden" asp-for="@Model[i].MightBeReserve" />
                    <input type="hidden" asp-for="@Model[i].SeatNumber" />
                    <input type="hidden" asp-for="@Model[i].BusScheduleId" />
                    <input type="hidden" name="Total" value="@total" />
                </div>



            }




        </div>
        <div class="col-md-3">
            <label class="h3"> Passenger Info </label>
            <br /><br />
            <div class="form-group">
                <label class="h4 control-label required-field"> Passenger Name</label>
                <input required class="form-control validate" name="PassengerName" />
            </div>
            <div class="form-group">
                <label class="h4 control-label required-field"> Passenger Mobile</label>
                <input required class="form-control validate" type="number" name="PassengerMobile" />
            </div>
            <p style="display:inline-block" class="h5"> <span class="SelectedCircle"></span> 	&nbsp;Selected Seat </p>
            <p style="display:inline-block" class="h5"> <span class="BookedCircle"></span> 	&nbsp;Already Booked </p>
            <p style="display:inline-block" class="h5"> <span class="AvailableCircle"></span> 		&nbsp;Available Seat</p>
            <label class="h5">Price of each Seat :@ViewBag.Price tk only</label><br />
            <input type="hidden" value="@ViewBag.Price" id="Price" />
            <label class="h5">Total Cost Is:<span id="TotalCost">0</span>Tk only</label><br />
            <label class="h5">Selected Seat</label><br />
            <span id="SetSelectedSeat"></span>

        </div>
    </div>
    
    <br />
    <div class="form-group col-md-4 col-md-offset-3" style="padding-top:20px;padding-right:40px">
        <input type="submit" value="Confirm Ticket" class="btn btn-success" />
        <a  asp-controller="TicketBooking" asp-action="Index" class="btn btn-danger"  >Cancel</a>
       
    </div>
</form>



@section Scripts{


    <script type="text/javascript">



        $(document).ready(function () {



            $("[id='status']").each(function () {
                var p = $(this).val();
                if ($(this).val() == 'true') {

                }
                console.log(p);
            })



            $('#ImageStatus img').click(function () {
                var seat = $(this).attr('alt');

                if ($("input[name*='[" + seat + "].ConfirmStatus']").val() == "True" &&
                    $("input[name*='[" + seat + "].MightBeReserve']").val() == "False"
                ) {
                    $(this).off('click');
                }
                else if ($("input[name*='[" + seat + "].ConfirmStatus']").val() == "False"
                    && $(this).attr('src') == "/images/Green.svg" &&
                    $("input[name*='[" + seat + "].MightBeReserve']").val() == "True"


                ) {


                    $(this).attr('src', "/images/Black.svg");
                    $("input[name*='[" + seat + "].ConfirmStatus']").val("True")
                    console.log(seat);
                    console.log("Take");



                } else if ($("input[name*='[" + seat + "].ConfirmStatus']").val() == "True"
                    && $(this).attr('src') == "/images/Black.svg" &&
                    $("input[name*='[" + seat + "].MightBeReserve']").val() == "True"


                ) {


                    $(this).attr('src', "/images/Green.svg");
                    $("input[name*='[" + seat + "].ConfirmStatus']").val("False")
                    console.log(seat);
                    console.log("Canceled");



                }
                else {

                    $(this).attr('src', "/images/Black.svg");
                    $("input[name*='[" + seat + "].ConfirmStatus']").val("True");
                    var a = $("input[name*='[" + seat + "].SeatNumber']").val();
                    //$("#SetSelectedSeat").html(a);
                    console.log(seat);
                    console.log("Take");
                }
                var seatFinal = "";
                var count = 1;
                for (var ami = 0; ami < $("input[name*='Total']").val(); ami++) {

                    if ($("input[name*='[" + ami + "].ConfirmStatus']").val() == "True"
                        &&
                        $("input[name*='[" + ami + "].MightBeReserve']").val() == "True"

                    )
                    {
                        seatFinal =seatFinal+count + ". " + $("input[name*='[" + ami + "].SeatNumber']").val()+ "<br>";
                        count++;
                    }

                }
                count = count - 1;
                var costIs=Number(count)* Number($("#Price").val());
                $("#SetSelectedSeat").html(seatFinal);
               
                $("#TotalCost").html(costIs);





            });









        });






    </script>


}

BlankSpace/Views/TicketBooking/ConfirmTicket.cshtml
@model BlankSpace.ViewModels.TicketVm
@{
    ViewData["Title"] = "ConfirmTicket";
}


<input style="margin-top:20px " type="button" id="print" value="Print Ticket!" class="btn btn-success"/><br /><br />


<div class="row" id="testdiv" style="padding-left:40px;padding-right:40px;color:darkred ">
    <div class="row" style="border-style:dashed;padding:10px 10px 10px 10px  ">
        <hr style="margin-top:7px;margin-bottom:1px;" />
        <hr style="margin-top:1px;margin-bottom:1px;" />
        <h4 style="text-align:center">White Space Bus </h4>
        <p>
            <b> <u>Route </u></b>  :@Model.StartFrom  --->  @Model.Destination
            <br />
            <b> <u>Issue Date </u></b>  :  @DateTime.Now

        </p>
        <hr style="margin-top:7px;margin-bottom:1px;" />
        <hr style="margin-top:1px;margin-bottom:10px;" />
        <div class="row">
            <div class="col-md-3">
                <b> <u>Passenger Name</u></b>

                <br />

                @Model.PassengerName
            </div>
            <div class="col-md-3">
                <b> <u>Mobile Number</u></b>
                <br />
                @Model.Mobile
            </div>
            <div class="col-md-3">
                <b> <u>Ticket Price</u></b><br />
                @Model.TicketPrice tk only
            </div>
            <div class="col-md-3">
                <b> <u>Seat Number</u></b><br />
                @for (int i = 0; i < Model.Seat.Count; i++)
                {
                    var a = Model.Seat[i].ToString();

                    <span class="h5">
                        @a



                        @if (i != Model.Seat.Count - 1)
                        {
                            <span>,</span>

                        }

                    </span>


                }
            </div>



        </div>

        <hr style="margin-top:7px;margin-bottom:1px;" />
        <hr style="margin-top:1px;margin-bottom:1px;" />
        <br />
        <div class="row">
            <div class="col-md-7">
                <div class="col-md-6">
                    <b><u>Bus Name( Coach )</u></b><br />
                    @Model.BusName
                    <br />
                    <b><u>Total Fare</u></b>
                    <br />
                    @Model.TotalCost tk only
                </div>
                <div class="col-md-6">
                    <div class="col-md-6">
                        <b><u>Reporting Time</u></b><br />
                        11 pm
                        <br />
                        <b><u>Departure Time</u></b>
                        <br />
                        @Model.Time
                    </div>
                </div>
            </div>

            <div class="col-md-5">
                <b><u>Bording Point Location </u></b>  <br />
                <b> <u> Jouney Start</u> </b>: @Model.StartFrom <br />
                <b><u>Destination</u></b>: @Model.Destination<br />
                <b><u>Date</u></b>: @Model.Date.ToString("dd/MM/yy")


            </div>
            <hr style="padding:1px" />


        </div>
        <hr style="margin-top:1px;margin-bottom:1px;" />
        <hr style="margin-top:1px;margin-bottom:1px;" />



    </div>


</div>


@section Scripts{

    <script type="text/javascript">
        

        $(document).ready(function () {


            $("#print").click(function () {


                var element = document.getElementById('testdiv');

        // Generate the PDF.
                const options = {
                    filename: 'Test.pdf',
                    image: { type: 'jpeg' },
                    html2canvas: {},
                    jsPDF: { orientation: 'Landscape', unit: 'in', format: 'letter', compressPDF: true }

                };
                html2pdf().from(element).set(options).save();
                
        //html2pdf().from(element).set({
        //  margin: .5,
        //  filename: 'test.pdf',
        //  html2canvas: { scale: 1 },
        //  jsPDF: {orientation: 'portrait', unit: 'in', format: 'letter', compressPDF: true}
        //}).save();







                


            });

        });


    </script>
}

BlankSpace/Views/TicketBooking/Index.cshtml
@model BlankSpace.ViewModels.BookingVm

@{
    ViewData["Title"] = "Index";
}



<div class="row">
    <div class="col-md-4 col-md-offset-4" style="border:dashed 2px green;padding:30px;margin-top:10px">
        <h4>Ticket Reservation Process</h4>
        <hr />
        <form asp-action="Booking" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="BookingVmId" />
                <label class="control-label h4"> Start the from  </label>
                <select asp-for="StartingFrom" asp-items="@ViewBag.Start" id="Start" class="form-control" >
                    <option hidden disabled selected> Please Select City</option>
                </select>
                <span asp-validation-for="StartingFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label h4"></label>
                <select asp-for="Destination" id="Des" class="form-control">
                </select>
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label h4"> Coach Name </label>
                <select id="bus" readonly class="form-control" asp-for="BusId"></select>
                <span asp-validation-for="BusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label h4"> Time </label>
                <input id="time" readonly class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label h4"></label>
                <input asp-for="Date" type="date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Check" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts{


    <script type="text/javascript">

        //insert the default value to the section

        $(document).ready(function () {
            var items = "<option value='0'>Select Your Place</option>";
            $("#Des").html(items);
        });
        //Set the section to select list according to class
        $("#Start").change(function () {
            if ($("#Start").val() == 0) {
                var items = "<option disabled selected hidden>Select Your Place </option>";
                $("#Des").html(items);
            }
            else {
                var Startid = $("#Start").val();
                var url = "/BusSchedule/check";
                $.getJSON(url, { id: Startid }, function (data) {
                    var items = "<option disabled selected hidden >Select Destinition  &#x2935</option>";
                    $("#Des").empty();
                    $.each(data, function (i, sec) {
                        items += '<option value="' + sec.value + '">' + sec.text + '</option > ';
                    });
                    $("#Des").html(items);

                });
                

            }
        });
        $("#Des").change(function () {
            if ($("#Des").val() == 0) {
                var items = "Select Your Place </opt";
                $("#Des").val(items);
            }
            else {

                var StartId = $("#Start").val();
                var DesId = $("#Des").val();
                var url = "/TicketBooking/checkboth";

                $.getJSON(url, { id: StartId, id2: DesId }, function (data) {
                    ////$("#bus").val("Select Your Place & Destination");
                    ////$("#bus").val(data);

                    $("#bus").empty();
                    $.each(data, function (i, sec) {
                        items += '<option value="' + sec.value + '">' + sec.text + '</option > ';
                    });
                    $("#bus").html(items);
                    if ($("#bus").val() == null) {
                        var items = "<option disabled selected hidden >No Record Found Try Another</option>";
                        $("#bus").html(items);
                        $("#time").val("No time");
                    }

                });


                var url = "/TicketBooking/checktime";

                $.getJSON(url, { id: StartId, id2: DesId }, function (data) {
                    $("#time").val(data);
                });
                var url = "/TicketBooking/checkid";

                $.getJSON(url, { id: StartId, id2: DesId }, function (data) {
                    var final = Number(data);

                    $("[name*='BookingVmId']").val(final);




                }
                );
            }
        });

    </script>

}

BlankSpace/Views/TicketBooking/Scripts.cshtml
@model BlankSpace.ViewModels.ScriptVm

@{
    ViewData["Title"] = "Genarate";
}




<div class="row">
    @ViewBag.SMS
    <div class="col-md-4 col-md-offset-4">

        <h1 class="text-center">Generate Scripts</h1>
        <hr />
        <form asp-action="ScriptsGenarate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BusId" class="control-label h4"></label>
                <select asp-items="@ViewBag.Bus" asp-for="BusId" class="form-control">
                    <option hidden disabled selected>Please Select Bus</option>
                </select>
                <span asp-validation-for="BusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label h4"></label>
                <input asp-for="Date" class="form-control" type="date" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Genrate" class="btn btn-success" />
            </div>
        </form>

    </div>
</div>

BlankSpace/Views/TicketBooking/ScriptsGenarate.cshtml
@model List<BlankSpace.ViewModels.ScriptVm>
@{
    ViewData["Title"] = "Scripts Genarate";
}

<h2>Scripts Genarate</h2>




<p>
    <input type="submit" class="btn btn-success" value="Make pdf " id="print" />
    <br />
</p>
<div id="testdiv">
   
    Coach Name : @Model[0].BusName <br />
    Route: @Model[0].Route >-----> @ViewBag.Destinaion
    <p class="h2" style="text-align:center;">Passenger List<br /><div style="border-bottom:1px solid #686868"></div> </p>

    <table class="table table-bordered table-responsive" >
        <thead>
            <tr>
                <th class="h3">
                    Serial No
                </th>
                <th class=" h3 ">
                    Passenger Name
                </th>
                <th class=" h3  ">
                    Mobile Number
                </th>
                <th class=" h3  ">
                    Seat Number
                </th>

            </tr>
        </thead>
        <tbody>
            @{ var a = 1;}
            @foreach (var item in Model)
            {
                <tr>

                    <td class=" h4  ">@a</td>
                    <td class=" h4  ">@item.Name</td>
                    <td class=" h4  ">@item.Mobile</td>
                    <td class=" h4  ">

                        @for (int i = 0; i < item.Seat.Count; i++)
                        {
                            var ab = item.Seat[i].ToString();

                            <span class="h5">
                                @ab

                                @if (i != item.Seat.Count - 1)
                                {
                                    <span>,</span>

                                }


                            </span>


                        }


                    </td>

                    @{a++;
                    }

                </tr>
            }
        </tbody>
    </table>

</div>


@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $("#print").click(function () {



                 var element = document.getElementById('testdiv');

        // Generate the PDF.
                const options = {
                    filename: 'Test.pdf',
                    image: { type: 'jpeg' },
                    margin: .5,
                    html2canvas: {},
                    jsPDF: { orientation: 'portrait', unit: 'in', format: 'letter', compressPDF: true }

                };
                html2pdf().from(element).set(options).save();





               




             
             
               

            });

        });


    </script>
}