BlankSpace/ViewModels/CreateExpenseViewModel.cs
using BlankSpace.Models;
using BlankSpace.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlankSpace.ViewModels
{
    public class CreateExpenseViewModel
    {
        public List<Buses> buslist;
        public Expense exp;

    }
}

BlankSpace/ViewModels/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlankSpace.ViewModels
{
    public class Expense
    {

        public int ExpenseId { get; set; }
        public int BusId { get; set; }
        public string BusName { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive number allowed")]
        public decimal Amount { get; set; }
        [Required]
        public string Narration { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public string DriverName { get; set; }
    }
}

BlankSpace/ViewModels/ExpenseSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlankSpace.ViewModels
{
    public class ExpenseSearch
    {
        public DateTime fromdate { get; set; }
        public DateTime todate { get; set; }
        public int busid { get; set; }


    }
}

BlankSpace/Controllers/ExpenseController.cs
using BlankSpace.Database;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlankSpace.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace BlankSpace.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly DatabaseContext _context;
        [TempData]
        public string msg { get; set; }
        public ExpenseController(DatabaseContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateExpense()
        {
            var expenseviewmodel = new Expense();
            var buslist = _context.Buses.ToList();
            ViewBag.buslist = buslist;
            return View(expenseviewmodel);
        }

        [HttpPost]
        public ActionResult CreateExpense(Expense ex)
        {
           
            _context.Expense.Add(ex);
            _context.SaveChanges();
            msg = "Expense Added Succesfully";
            return RedirectToAction(nameof(CreateExpense));
        }

        public IActionResult GetExpensebybusId()
        {
            var expenS = new ExpenseSearch();
            var buslist = _context.Buses.ToList();
            ViewBag.buslist = buslist;
            return View(expenS);
        }
    
        public IActionResult ExpenseReport(DateTime fromdate,DateTime todate,int Busid)
        {
            var expenslist = _context.Expense.Where(x => x.Date >= fromdate && x.Date <= todate && x.BusId == Busid).ToList();
            return View(expenslist);
        }


        public IActionResult ExpenseList()
        {
            if (HttpContext.Session.GetString("UserRole") != null)
            {
                var s = _context.Expense.AsNoTracking().ToList();
                var dr = new List<Expense>();
                //int c = 1;
                foreach (var item in s)
                {
                    Expense se = new Expense()
                    {
                        ExpenseId = item.ExpenseId,
                        BusId = item.BusId,
                        Date = item.Date,
                        Amount = item.Amount,
                        Narration = item.Narration,
                        DriverName = item.DriverName
                    };
                    //se.ExpenseId = c;
                    //c++;
                    dr.Add(se);
                }
                return View(dr);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public IActionResult UpdateExpense(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var item = _context.Expense.AsNoTracking().Where(s => s.ExpenseId == id).FirstOrDefault();
                Expense aa = new Expense()
                {
                    ExpenseId = item.ExpenseId,
                    BusId = item.BusId,
                    Date = item.Date,
                    Amount = item.Amount,
                    Narration = item.Narration,
                    DriverName = item.DriverName
                };
                return View(aa);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }
        [HttpPost]
        public IActionResult UpdateExpense(Expense val)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                //var che = _context.Expense.Where(x => x.ExpenseId == val.ExpenseId ).FirstOrDefault();
                Expense di = new Expense()
                {
                    ExpenseId = val.ExpenseId,
                    BusId = val.BusId,
                    Date = val.Date,
                    Amount = val.Amount,
                    Narration = val.Narration,
                    DriverName = val.DriverName

                };
               
                    _context.Expense.Update(di);
                    _context.SaveChanges();
                    msg = "Expense Updated Successfully";
                    return RedirectToAction(nameof(ExpenseList));
               

            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }


        public IActionResult ExpenseDetails(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var details = _context.Expense.AsNoTracking().Where(s => s.ExpenseId == id).FirstOrDefault();

                Expense a = new Expense()
                {
                    ExpenseId = details.ExpenseId,
                    BusId = details.BusId,
                    Date = details.Date,
                    Amount = details.Amount,
                    Narration = details.Narration,
                    DriverName = details.DriverName
                };

                return View(a);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public IActionResult DeleteExpense(int id)
        {
            if (HttpContext.Session.GetString("UserRole") == "1")
            {
                var item = _context.Expense.AsNoTracking().Where(s => s.ExpenseId == id).FirstOrDefault();
                Expense se = new Expense()
                {
                    ExpenseId = item.ExpenseId,
                    BusId = item.BusId,
                    Date = item.Date,
                    Amount = item.Amount,
                    Narration = item.Narration,
                    DriverName = item.DriverName

                };
                return View(se);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public IActionResult DeleteExpense(Expense se)
        {
            _context.Expense.Remove(_context.Expense.AsNoTracking().Where(s => s.ExpenseId == se.ExpenseId).FirstOrDefault());
            _context.SaveChanges();
            msg = "Deleted Successfully";
            return RedirectToAction("ExpenseList");
        }

    }
}

BlankSpace/Views/Expense/CreateExpense.cshtml
@model BlankSpace.ViewModels.Expense

@{
    ViewData["Title"] = "CreateExpense";
}
<h2 style="text-align:center">Create Expense</h2>
<hr />


<div class="row">
    <div class="col-md-4 col-md-offset-4">

        @if (TempData["msg"] != null)
        {
            <div class="alert alert-info text-center" role="alert">
                <button type="button" class="close" aria-label="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                @TempData["msg"]
            </div>
        }
        <form asp-action="CreateExpense">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @*<div class="form-group">
                <label asp-for="ExpenseId" class="control-label h4"></label>
                <input asp-for="ExpenseId" class="form-control" />
                <span asp-validation-for="ExpenseId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                @*<label asp-for="BusId" class="control-label h4"></label>
            <input asp-for="BusId" class="form-control" />
            <span asp-validation-for="BusId" class="text-danger"></span>*@
                <h4>Select Bus</h4>
                @Html.DropDownListFor(M => M.BusId, new SelectList(ViewBag.buslist, "BusId", "CoachName"))
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label h4"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>

            @*<div class="form-group">
                <label asp-for="BusName" class="control-label h4"></label>
                <input asp-for="BusName" class="form-control" />
                <span asp-validation-for="BusName" class="text-danger"></span>
            </div>*@

            <div class="form-group">
                <label asp-for="Narration" class="control-label h4"></label>
                <input asp-for="Narration" class="form-control" />
                <span asp-validation-for="Narration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label h4"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverName" class="control-label h4"></label>
                <input asp-for="DriverName" class="form-control" />
                <span asp-validation-for="DriverName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
        <div>
            <a asp-action="ExpenseList">Back to List</a>
        </div>
    </div>
</div>

BlankSpace/Views/Expense/DeleteExpense.cshtml
@model BlankSpace.ViewModels.Expense

@{
    ViewData["Title"] = "Delete Expense";
}

<h2 style="text-align: center;">Delete Expense</h2>
<hr />
<h3 style="text-align: center;">Are you sure you want to delete this?</h3>
<div class="col-md-5 col-md-offset-4">

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.ExpenseId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExpenseId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BusId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BusId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Narration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Narration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriverName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverName)
        </dd>

    </dl>

    <form asp-action="DeleteExpense">
        <input type="hidden" asp-for="ExpenseId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ExpenseList">Back to Expense List</a>
    </form>
</div>

BlankSpace/Views/Expense/ExpenseDetails.cshtml
@model BlankSpace.ViewModels.Expense

@{
    ViewData["Title"] = "ExpenseDetails";
}
<script>

        function printDiv() {
            var divContents = document.getElementById("GFG").innerHTML;
            var a = window.open('', '', '', '', '', '');
            a.document.write(divContents);
            a.document.close();
            a.print();
        }
</script>
<div id="GFG">
    <h2 style="text-align:center">
        <strong>Expense Details </strong>
    </h2>
    <hr />
    <input type="button" value="Print" onclick="printDiv()">
    <div class="col-md-4 col-md-offset-4">



        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ExpenseId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ExpenseId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.BusId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BusId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Narration)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Narration)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DriverName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DriverName)
            </dd>
        </dl>
        <div>
            <a asp-action="ExpenseList">Back to Expense List</a>
        </div>

    </div>
</div>

BlankSpace/Views/Expense/ExpenseList.cshtml
@model List<BlankSpace.ViewModels.Expense>

<p class="h2" style="text-align:center;">Expense List For All Vehicle<br /><div style="border-bottom:1px solid #686868"></div> </p>

@if (TempData["msg"] != null)
{
    <div class="alert alert-info text-center" role="alert">
        <button type="button" class="close" aria-label="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["msg"]
    </div>
}
<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th class="h3">
                Bus Id
            </th>
            <th class="h3">
                Date
            </th>
            <th class=" h3  ">
                Amount
            </th>
            <th class=" h3  ">
                Narration
            </th>
            <th class=" h3  ">
                Driver Name
            </th>
            <th class=" h3  ">
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td class=" h4  ">@item.BusId</td>
                <td class=" h4  ">@item.Date</td>
                <td class=" h4  ">@item.Amount</td>
                <td class=" h4  ">@item.Narration</td>
                <td class=" h4  ">@item.DriverName</td>

                <td class=" h4  ">
                    <a asp-action="UpdateExpense" asp-controller="Expense" asp-route-id="@item.ExpenseId"><i class="fa fa-pencil-square-o" style="font-size:25px;color:green"></i></a>
                    &nbsp;&nbsp;&nbsp;
                    <a asp-action="ExpenseDetails" asp-controller="Expense" asp-route-id="@item.ExpenseId"><i class="fa fa-info-circle" style="font-size:25px;color:dodgerblue"></i></a>
                    &nbsp;&nbsp;&nbsp;
                    <a asp-action="DeleteExpense" asp-controller="Expense" asp-route-id="@item.ExpenseId"><i class="fa fa-trash" style="font-size:25px;color:red"></i></a>

                </td>
            </tr>
        }
    </tbody>
</table>

BlankSpace/Views/Expense/ExpensePrint.cshtml
@model List<BlankSpace.ViewModels.Expense>

<p class="h2" style="text-align:center;">Expense Report<br /><div style="border-bottom:1px solid #686868"></div> </p>
<a class="btn btn-default" asp-controller="Expense" asp-action="ExpensePrint"><i class="fa fa-print" aria-hidden="true" style="    font-size: 17px;"> Print</i></a>
@if (TempData["msg"] != null)
{
    <div class="alert alert-info text-center" role="alert">
        <button type="button" class="close" aria-label="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["msg"]
    </div>
}


<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th class="h3">
                Bus Id
            </th>
            <th class="h3">
                Amount
            </th>
            <th class="h3">
                Narration
            </th>
            <th class="h3">
                Date
            </th>
            <th class=" h3 ">
                Driver Name
            </th>
            <th class=" h3  ">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td class=" h4  ">@item.BusId</td>
                @*<td class=" h4  ">@item.BusName</td>*@
                <td class=" h4  ">@item.Amount</td>
                <td class=" h4  ">@item.Narration</td>
                <td class=" h4  ">@item.Date</td>
                <td class=" h4  ">@item.DriverName</td>

                <td class=" h4  ">
                    @*<a asp-action="UpdateNotice" asp-controller="Expense" asp-route-id="@item.BusId"><i class="fa fa-pencil-square-o" style="font-size:25px;color:green"></i></a>
                        &nbsp;&nbsp;&nbsp;*@
                    <a asp-action="ExpenseDetails" asp-controller="Expense" asp-route-id="@item.BusId"><i class="fa fa-info-circle" style="font-size:25px;color:dodgerblue"></i></a>
                    &nbsp;&nbsp;&nbsp;
                    <a asp-action="DeleteExpense" asp-controller="Expense" asp-route-id="@item.BusId"><i class="fa fa-trash" style="font-size:25px;color:red"></i></a>

                </td>
            </tr>
        }
    </tbody>
</table>

BlankSpace/Views/Expense/ExpenseReport.cshtml
@model List<BlankSpace.ViewModels.Expense>

    <script>

        function printDiv() {
            var divContents = document.getElementById("GFG").innerHTML;
            var a = window.open('', '', '', '', '', '');
            a.document.write(divContents);
            a.document.close();
            a.print();
        }
    </script>

 
 <div id="GFG">

     <p class="h2" style="text-align:center;">Expense Report<br /><div style="border-bottom:1px solid #686868"></div> </p>
     <input type="button" value="Print" onclick="printDiv()">
     @if (TempData["msg"] != null)
     {
         <div class="alert alert-info text-center" role="alert">
             <button type="button" class="close" aria-label="close" data-dismiss="alert">
                 <span aria-hidden="true">&times;</span>
             </button>
             @TempData["msg"]
         </div>
     }
     <table class="table table-striped table-responsive">
         <thead>
             <tr>
                 <th class="h3">
                     Bus Id
                 </th>
                 <th class="h3">
                     Amount
                 </th>
                 <th class="h3">
                     Narration
                 </th>
                 <th class="h3">
                     Date
                 </th>
                 <th class=" h3 ">
                     Driver Name
                 </th>
                 <th class=" h3  ">
                     Action
                 </th>
             </tr>
         </thead>
         <tbody>
             @foreach (var item in Model)
             {
                 <tr>

                     <td class=" h4  ">@item.BusId</td>
                     @*<td class=" h4  ">@item.BusName</td>*@
                     <td class=" h4  ">@item.Amount</td>
                     <td class=" h4  ">@item.Narration</td>
                     <td class=" h4  ">@item.Date</td>
                     <td class=" h4  ">@item.DriverName</td>

                     <td class=" h4  ">
                         @*<a asp-action="UpdateNotice" asp-controller="Expense" asp-route-id="@item.BusId"><i class="fa fa-pencil-square-o" style="font-size:25px;color:green"></i></a>
                            &nbsp;&nbsp;&nbsp;*@
                         <a asp-action="ExpenseDetails" asp-controller="Expense" asp-route-id="@item.BusId"><i class="fa fa-info-circle" style="font-size:25px;color:dodgerblue"></i></a>
                         &nbsp;&nbsp;&nbsp;
                         <a asp-action="DeleteExpense" asp-controller="Expense" asp-route-id="@item.BusId"><i class="fa fa-trash" style="font-size:25px;color:red"></i></a>

                     </td>
                 </tr>
             }
         </tbody>
     </table>



 </div>
    

BlankSpace/Views/Expense/ExpenseSearchs.cshtml
@model BlankSpace.ViewModels.ExpenseSearch

@{
    ViewData["Title"] = "CreateExpense";
}
<h2 style="text-align:center">Create Expense</h2>
<hr />


<div class="row">
    <div class="col-md-4 col-md-offset-4">

        @*@if (TempData["msg"] != null)
            {
                <div class="alert alert-info text-center" role="alert">
                    <button type="button" class="close" aria-label="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @TempData["msg"]
                </div>
            }*@
        <form asp-action="GetExpensebybusId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!--<!--<div class="form-group">-->-->
                <!--@*<label asp-for="BusId" class="control-label h4"></label>
                    <input asp-for="BusId" class="form-control" />
                    <span asp-validation-for="BusId" class="text-danger"></span>*@-->
                <!--
            </div>-->
        <div class="form-group">
            @Html.DropDownListFor(M => M.busid, new SelectList(ViewBag.buslist, "BusId", "CoachName"))

        </div>

            <div class="form-group">
                <label asp-for="fromdate" class="control-label h4"></label>
                <input asp-for="fromdate" class="form-control" />
                <span asp-validation-for="fromdate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="todate" class="control-label h4"></label>
                <input asp-for="todate" class="form-control" />
                <span asp-validation-for="todate" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="View" class="btn btn-default" />
            </div>
        </form>
        <div>
            <a asp-action="ExpenseList">Back to List</a>
        </div>
    </div>
</div>

BlankSpace/Views/Expense/GetExpensebybusId.cshtml
@model BlankSpace.ViewModels.ExpenseSearch

@{
    ViewData["Title"] = "CreateExpense";
}
<h2 style="text-align:center">Expense Report</h2>
<hr />


<div class="row">
    <div class="col-md-4 col-md-offset-4">

        @*@if (TempData["msg"] != null)
            {
                <div class="alert alert-info text-center" role="alert">
                    <button type="button" class="close" aria-label="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @TempData["msg"]
                </div>
            }*@
        <form asp-action="ExpenseReport">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!--<!--<div class="form-group">-->
            <!--@*<label asp-for="BusId" class="control-label h4"></label>
                <input asp-for="BusId" class="form-control" />
                <span asp-validation-for="BusId" class="text-danger"></span>*@-->
            <!--
            </div>-->
            <div class="form-group">
                <h4>Select Bus</h4>
                @Html.DropDownListFor(M => M.busid, new SelectList(ViewBag.buslist, "BusId", "CoachName"))

            </div>

            <div class="form-group">
                <label asp-for="fromdate" class="control-label h4">From Date</label>
                <input asp-for="fromdate" class="form-control" />
                <span asp-validation-for="fromdate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="todate" class="control-label h4">To Date</label>
                <input asp-for="todate" class="form-control" />
                <span asp-validation-for="todate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="View" class="btn btn-default" />
            </div>
        </form>
        <div>
            <a asp-action="ExpenseList">Back to Expense List</a>
        </div>
    </div>
</div>

BlankSpace/Views/Expense/UpdateExpense.cshtml
@model BlankSpace.ViewModels.Expense

@{
    ViewData["Title"] = "UpdateExpense";
}

<h2 style="text-align:center">Update Expense</h2>

<hr />
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @if (TempData["msg"] != null)
        {
            <div class="alert alert-info text-center" role="alert">
                <button type="button" class="close" aria-label="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                @TempData["msg"]
            </div>
        }
    <form asp-controller="Expense" asp-action="UpdateExpense" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input asp-for="ExpenseId" type="hidden" />
        <input asp-for="BusId" type="hidden" />

        <div class="form-group">
            <label asp-for="Date" class="control-label"></label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Amount" class="control-label"></label>
            <input asp-for="Amount" class="form-control" />
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Narration" class="control-label"></label>
            <input asp-for="Narration" class="form-control" />
            <span asp-validation-for="Narration" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DriverName" class="control-label"></label>
            <input asp-for="DriverName" class="form-control" />
            <span asp-validation-for="DriverName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </form>
        <div>
            <a asp-action="ExpenseList">Back to Expense List</a>
        </div>
    </div>
</div>